import localFont from "next/font/local";
import "./globals.css";

const ahamaticServiceAccount = {
  apiKey: '881c0820-7a7a-11ec-b207-8dd119227be1',
  emailAddress: 'developers@volenday.com',
  password: 'V0l3nd@yP@ssw0rd',
  rememberMe: true
}

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
